Insert Client
projetoKhali/API2Semestre pull request #106
Opened 2023-05-13 17:47 UTC by Incivius

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #90 

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

 - 

<br>

# 🐞Bugs <br>  
`Essa entrega inclui algum bug não-solucionado? Cite-o(s)`

 - 

<br>

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

- 

<br>

2023-05-13 23:33 UTC, paulo-granthon approved these changes

2023-05-14 06:58 UTC, paulo-granthon requested changes

2023-05-14 06:58 UTC, paulo-granthon commented on SQL/tabelas.sql
faltando tabela `cliente`

2023-05-14 06:58 UTC, paulo-granthon commented on src/main/java/org/openjfx/API2Semestre/database/query/TableProperty.java
> +    // TODO: Clients table
faltando valores:
```java 
RazaoSocial("...")
CNPJ("...")
```
Referenciadas em `QueryLibs.insertClient()`: linhas 465 e 466

2023-05-14 06:58 UTC, paulo-granthon commented on src/main/java/org/openjfx/API2Semestre/database/query/QueryTable.java
>      // TODO: Client,
faltando tabela:
```java 
Client("...")
```
Referenciada em `QueryLibs.insertClient()`: linha 463

2023-05-15 00:36 UTC, taniacruzz approved these changes

2023-05-15 00:38 UTC, taniacruzz commented
![burndown3](https://github.com/projetoKhali/API2Semestre/assets/79020769/5d22af8b-32fa-4b3e-a1a2-9152b4d327c2)

2023-05-15 00:38 UTC, paulo-granthon approved these changes

2023-05-15 00:39 UTC, merged