Atualizando tabelas e views
projetoKhali/API2Semestre pull request #132
Opened 2023-05-27 18:24 UTC by JhonatanLop

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #116 

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

 - 

<br>

# 🐞Bugs <br>  
`Essa entrega inclui algum bug não-solucionado? Cite-o(s)`

 - aplicação não é iniciada por conta de import desatualizado

<br>

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

- foi adicionado uma clausula no join da view "left" a fim de tentar minimizar os erros e melhorar a velocidade do select 

<br>

2023-05-27 19:34 UTC, paulo-granthon approved these changes

2023-05-28 21:16 UTC, paulo-granthon requested changes

2023-05-28 21:16 UTC, paulo-granthon commented on SQL/views.sql
> +    apontamento .hora_fim,
?

2023-05-28 21:17 UTC, paulo-granthon commented on SQL/views.sql
> +    apontamento .hora_fim,
```suggestion
    apontamento.hora_fim,
```

2023-05-29 00:03 UTC, paulo-granthon approved these changes

2023-06-04 21:23 UTC, Incivius approved these changes

2023-06-04 21:37 UTC, merged