Funcionalidade de alteração de senha
projetoKhali/API2Semestre pull request #140
Opened 2023-06-03 19:49 UTC by Incivius

# 🥳 Conclusão de tarefa <br>  
`Insira o #ID do(s) Issue(s) que essa entrega conclui no seguinte formato: "resolve #ID"`  

- resolve #130 

<br>

# 🚀 Extras <br>  
`Essa entrega inclui alguma feature extra concluída ou em progress? Cite-a(s)`

 - 

<br>

# 🐞Bugs <br>  
`Essa entrega inclui algum bug não-solucionado? Cite-o(s)`

 - 

<br>

# 🏅 Comentários adicionais <br>  
`Algo mais que gostaria de comentar com a equipe a respeito da entrega dessa tarefa?`

- 

<br>

2023-06-03 20:05 UTC, paulo-granthon requested changes

2023-06-03 20:05 UTC, paulo-granthon commented on src/main/java/org/openjfx/API2Semestre/authentication/User.java
> +    public User (){}
```suggestion
```

2023-06-04 21:29 UTC, paulo-granthon approved these changes

2023-06-04 22:10 UTC, taniacruzz approved these changes

2023-06-04 22:10 UTC, merged