Sql insert
projetoKhali/API2Semestre pull request #46
Opened 2023-04-12 16:56 UTC by Incivius

# Numero do issue
Insira o ID da tarefa após o "#":  
resolve #17

# Comentários adicionais:

2023-04-12 17:51 UTC, paulo-granthon commented on src/JavaFiles/QueryLibs.java
> +        String sql = "INSERT INTO tabela_teste (apt_id, hora_inicio, hora_fim, usr_id, projeto, cliente, tipo, justificativa, cr_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
lembrar de trocar `tabela_teste` pelo nome da tabela que será usada

2023-04-12 18:03 UTC, paulo-granthon submitted a review, later dismissed
PR aprovado, conversaremos sobre os pontos mencionados nos comentários

2023-04-12 21:12 UTC, JhonatanLop commented on src/JavaFiles/QueryLibs.java
> +        String sql = "INSERT INTO tabela_teste (apt_id, hora_inicio, hora_fim, usr_id, projeto, cliente, tipo, justificativa, cr_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
não é necessário passar o id como parâmetro no insert pois é gerado automaticamente no banco

2023-04-12 21:13 UTC, JhonatanLop commented on src/JavaFiles/QueryLibs.java
> +        String sql = "INSERT INTO tabela_teste (apt_id, hora_inicio, hora_fim, usr_id, projeto, cliente, tipo, justificativa, cr_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
nome da tabela: apontamento

2023-04-12 21:13 UTC, JhonatanLop commented on src/JavaFiles/QueryLibs.java
> +        String sql = "INSERT INTO tabela_teste (apt_id, hora_inicio, hora_fim, usr_id, projeto, cliente, tipo, justificativa, cr_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
nome da tabela: apontamento

2023-04-12 21:19 UTC, JhonatanLop requested changes
apenas alguns ajustes.
- mudar nome da tabela para "apontamento"
- "id" já é gerado automaticamente, portanto não precisar ser passado como parâmetro para um insert

2023-04-12 23:19 UTC, JhonatanLop submitted a review, later dismissed
tudo certo meu nobre

2023-04-16 01:08 UTC, JhonatanLop reviewed
apenas um apontamento:
mudar o local da conversão, mas permanecer os atributos do tipo timestamp. que é equivalente ao LocalDateTime no SQL

2023-04-16 01:08 UTC, JhonatanLop commented on src/Classes/Appointment.java
> +    private Timestamp startDate;       // Data de início do apontamento.
os tipos precisam estar em timestamp

2023-04-16 01:08 UTC, JhonatanLop commented on src/JavaFiles/SQLConnection.java
> +            LocalDateTime startDate = LocalDateTime.of(2009, 12, 25, 10, 07, 59);
é preciso achar um lugar melhor pra fazer essa conversão

2023-04-16 17:43 UTC, paulo-granthon commented on src/Classes/Appointment.java
> +    private Integer id;                 // Identificação unica do apontamento.
Utilizando a classe Integer em vez do primitivo int conseguimos ter um id nulo representando um apontamento que será criado no momento e ainda não possui id autogerado. 

Caso o apontamento esteja sendo "carregado" do banco de dados através de uma quey, conseguimos associar o id existente ao objeto do tipo Appointment

2023-04-16 17:44 UTC, paulo-granthon commented on src/Classes/Appointment.java
> +        this.id = null;
construtor de Appointment para a criação de novos apontamentos a serem posteriormente salvos no banco de dados

2023-04-16 17:45 UTC, paulo-granthon commented on src/Classes/Appointment.java
> +        this.id = id;
construtor de Appointment com id parametro para o carregamento de apontamentos existentes no banco de dados.

2023-04-16 17:46 UTC, paulo-granthon commented on src/Classes/Appointment.java
> +    public Integer getId() { return id; }
```java
getId()
```
agora retorna Integer pois pode ser int ou null

2023-04-16 17:49 UTC, paulo-granthon commented on src/JavaFiles/SQLConnection.java
> +            LocalDateTime startDate = LocalDateTime.of(2009, 12, 25, 10, 07, 59);
conversão movida para o parametro de `TimeStamp.valueOf`.
Removidas: `startDate` & `endDate`.

2023-04-16 21:32 UTC, JhonatanLop reviewed
alguns apontamentos que vão vir como atualizações.
- campo de centro de resultado será inteiro

2023-04-16 21:33 UTC, JhonatanLop reviewed
certin

2023-04-16 21:35 UTC, JhonatanLop reviewed
será necessário atualizações, mas por enquanto tudo certo

2023-04-16 21:37 UTC, JhonatanLop approved these changes
certin

2023-04-16 21:38 UTC, JhonatanLop reviewed
certin

2023-04-17 23:24 UTC, JhonatanLop requested changes
falta só mudar o tipo do dado de insert de int pra String.

2023-04-18 17:04 UTC, taniacruzz approved these changes

2023-04-18 18:09 UTC, merged