Sql update
projetoKhali/API2Semestre pull request #48
Opened 2023-04-15 17:49 UTC by Incivius

# Numero do issue
Insira o ID da tarefa após o "#":  
resolve #45

# Comentários adicionais:
No arquivo QueryLibs eu inseri métodos de Update e Delete, a base dessas funções é o ID do apontamento.

2023-04-15 21:05 UTC, paulo-granthon commented on src/App.java
> +import super::JavaFiles;
👎

2023-04-15 21:08 UTC, paulo-granthon commented on src/JavaFiles/QueryLibs.java
> +        String sql = "UPDATE apontamento SET apt_id = ?, hora_inicio = ?, hora_fim = ?, usr_id = ?, projeto = ?, cliente = ?, tipo = ?, cr_id = ? WHERE apt_id = ?";
Nesse caso haveria a possibilidade de modificar o ID de um apontamento. Acredito que não deveria ser possivel fazer essa alteração.

2023-04-15 21:13 UTC, paulo-granthon commented on src/JavaFiles/QueryLibs.java
> +            statement.setObject(1, Date.from(Apt.getStartDate().atZone(ZoneId.systemDefault()).toInstant()));
Indice 1 nesse caso se refere a 
```sql
apt_id = ?
```
Nesse caso seria id 2.  

Porém,   

Caso vá remover a possibilidade de alterar ID no update, estaria correto chamar com índice 1.
```java
statement.setObject(1, Date.from(Apt.getStartDate().atZone(ZoneId.systemDefault()).toInstant()));
```

2023-04-15 21:14 UTC, paulo-granthon requested changes
Referente aos meus 3 comentários anteriores

2023-04-17 22:19 UTC, JhonatanLop commented on src/JavaFiles/QueryLibs.java
> +        String sql = "UPDATE apontamento SET apt_id = ?, hora_inicio = ?, hora_fim = ?, usr_id = ?, projeto = ?, cliente = ?, tipo = ?, cr_id = ? WHERE apt_id = ?";
treu, confirmo o comentário do paulo

2023-04-17 23:04 UTC, paulo-granthon approved these changes

2023-04-18 20:12 UTC, JhonatanLop requested changes
ignorar tipo dos dados no merge

2023-04-18 20:13 UTC, JhonatanLop approved these changes
ignorar tipo dos dado sno merge

2023-04-18 20:18 UTC, merged